# Page settings

baseURL = "https://lukasretschmeier.netlify.com/"
languageCode = "en"
title = "Lukas Retschmeier"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-163506805-1"


[params]
    author = "Lukas Retschmeier"
    description = "Lukas Retschmeier Resume"

    primaryColor = "#FF6460"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Lukas Retschmeier"
        tagline = "Junior IT Consultant PLM, Developer"
        avatar = "avatar.png"

    [params.contact]
        enable = true
        location = "Munich"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+4915254548176"
        text = "1525 45 58 176"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:retschmeier.lukas@gmail.com"
        text = "retschmeier.lukas@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://www.lukasretschmeier.de"
        text = "www.lukasretschmeier.de"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Java"
        [[params.skills.list.items]]
        details = "Containerization (Docker)"
        [[params.skills.list.items]]
        details = "IR Systems (Elastic Stack)"
        [[params.skills.list.items]]
        details = "JavaScript: React/Vue"
        
        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Agile Principles (SCRUM)"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"

        [[params.skills.list]]
        title = "Informatics"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Computer Science"
        university = "Technical University Mannheim"
        dates = "2019 - ongoing"
        [[params.education.list]]
        degree = "BSc in Computer Science (ECTS Grade A, 1.4)"
        university = "Duale Hochschule Baden-Württemberg Mannheim"
        dates = "2015 - 2018"
        [[params.education.list]]
        degree = "A-Levels (1.8)"
        university = "Gymnasium Dingolfing"
        dates = "2007 - 2015"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "DHBW Mannheim"
        body = "Honored as Best Graduate"
        date = "2018"
        [[params.awards.list]]
        name = "Deutscher Musikrat"
        body = "First Price regional competition Jugend Musiziert"
        date = "2013"

    [params.languages]
        enable = true
        [[params.languages.list]]
           name = "German"
         level = "Native"
        [[params.languages.list]]
            name = "English"
            level = "Business Fluent, C1"
        [[params.languages.list]]
          name = "Latin"
           level = "Latinum"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Piano"
        [[params.interests.list]]
        name = "Volleyball"
        [[params.interests.list]]
        name = "Reading"

    [params.summary]
        enable = true
        text = "xxxxxxx"

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Junior IT Consultant PLM"
        dates = "2018 - Present"
        company = "Atos Information Technology"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."


        [[params.experience.list]]
        title = "Student Research Assistant"
        dates = "2016 - 2018"
        company = "Optes"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Dualer Study Degree Program"
        dates = "2015 - 2018"
        company = "Atos Information Technology"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Piano, Volleyball, Reading"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/lukas681"
        title = "lukas681"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/lukas-retschmeier-024a64117"
        title = "lukas-retschmeier"




